#!/usr/bin/env python3
"""
Telegram-бот для управления датами туров на сайте «Ну погоди, весь мир».
Запуск: ./venv/bin/python3 bot.py
"""

import json
import logging
import os
import subprocess

from telegram import InlineKeyboardButton, InlineKeyboardMarkup, Update
from telegram.ext import (
    Application,
    CallbackQueryHandler,
    CommandHandler,
    ContextTypes,
    ConversationHandler,
    MessageHandler,
    filters,
)

# ===== Configuration =====
BOT_TOKEN = os.environ["BOT_TOKEN"]
ADMIN_USER_ID = int(os.environ["ADMIN_USER_ID"])
PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))
DATA_FILE = os.path.join(PROJECT_DIR, "tours_data.json")
DATA_JS_FILE = os.path.join(PROJECT_DIR, "tours_data.js")

TOUR_NAMES = {
    "tour1": "🏛 Бурятия: культура, быт и природа",
    "tour2": "🌊 Сахалин: на краю света",
}

# Conversation states
WAITING_NEW_DATE = 1
WAITING_NEW_SPOTS = 2
WAITING_EDIT_SPOTS = 3

logging.basicConfig(
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
    level=logging.INFO,
)
logger = logging.getLogger(__name__)


# ===== Data helpers =====
def git_push():
    """Commit and push data files to GitHub so the website updates."""
    try:
        subprocess.run(
            ["git", "add", "tours_data.json", "tours_data.js"],
            cwd=PROJECT_DIR, check=True, capture_output=True,
        )
        subprocess.run(
            ["git", "commit", "-m", "🔄 Обновление данных туров (бот)"],
            cwd=PROJECT_DIR, check=True, capture_output=True,
        )
        subprocess.run(
            ["git", "push"],
            cwd=PROJECT_DIR, check=True, capture_output=True,
        )
        logger.info("✅ Данные запушены в GitHub")
    except subprocess.CalledProcessError as e:
        logger.warning(f"⚠️ Git push не удался: {e.stderr}")


def load_data() -> dict:
    with open(DATA_FILE, "r", encoding="utf-8") as f:
        return json.load(f)


def save_data(data: dict) -> None:
    with open(DATA_FILE, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    # Also write JS version for file:// protocol compatibility
    with open(DATA_JS_FILE, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by bot.py — do not edit manually\n")
        f.write("var TOURS_DATA = ")
        json.dump(data, f, ensure_ascii=False, indent=2)
        f.write(";\n")
    # Push to GitHub Pages
    git_push()


def spots_label(spots: int) -> str:
    if spots <= 0:
        return "🔴 Мест нет"
    elif spots <= 3:
        return f"🟡 Осталось {spots}"
    else:
        return f"🟢 Мест: {spots}"


def is_admin(user_id: int) -> bool:
    return user_id == ADMIN_USER_ID


# ===== Handlers =====
async def start(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    logger.info(f"📩 /start от user_id={update.effective_user.id}, username={update.effective_user.username}")
    if not is_admin(update.effective_user.id):
        await update.message.reply_text(f"⛔ Доступ запрещён. Ваш ID: {update.effective_user.id}")
        return

    await update.message.reply_text(
        "👋 Привет! Я бот для управления датами туров.\n\n"
        "Команды:\n"
        "/tours — управление турами\n"
        "/help — справка",
    )


async def help_cmd(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    if not is_admin(update.effective_user.id):
        return
    await update.message.reply_text(
        "📖 *Справка*\n\n"
        "/tours — показать туры\n"
        "Выберите тур → увидите даты\n"
        "Для каждой даты можно:\n"
        "• ✏️ Изменить кол-во мест\n"
        "• 🗑 Удалить дату\n"
        "• ➕ Добавить новую дату\n\n"
        "Сайт подхватит изменения при перезагрузке страницы.",
        parse_mode="Markdown",
    )


async def tours(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    if not is_admin(update.effective_user.id):
        await update.message.reply_text("⛔ Доступ запрещён.")
        return

    keyboard = [
        [InlineKeyboardButton(name, callback_data=f"tour:{key}")]
        for key, name in TOUR_NAMES.items()
    ]
    await update.message.reply_text(
        "🗺 Выберите тур:",
        reply_markup=InlineKeyboardMarkup(keyboard),
    )


async def tour_selected(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    query = update.callback_query
    await query.answer()

    if not is_admin(query.from_user.id):
        return

    tour_key = query.data.split(":")[1]
    await show_tour_dates(query, context, tour_key)


async def show_tour_dates(query, context, tour_key: str) -> None:
    data = load_data()
    dates = data.get(tour_key, [])
    tour_name = TOUR_NAMES.get(tour_key, tour_key)

    text = f"📅 *{tour_name}*\n\n"

    keyboard = []
    for i, item in enumerate(dates):
        label = spots_label(item["spots"])
        text += f"{i + 1}. {item['date']} — {label}\n"
        keyboard.append([
            InlineKeyboardButton(
                f"{item['date']}",
                callback_data=f"date:{tour_key}:{i}",
            )
        ])

    if not dates:
        text += "Дат пока нет.\n"

    keyboard.append([
        InlineKeyboardButton("➕ Добавить дату", callback_data=f"add:{tour_key}")
    ])
    keyboard.append([
        InlineKeyboardButton("◀️ Назад к турам", callback_data="back:tours")
    ])

    await query.edit_message_text(
        text,
        reply_markup=InlineKeyboardMarkup(keyboard),
        parse_mode="Markdown",
    )


async def date_selected(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    query = update.callback_query
    await query.answer()

    if not is_admin(query.from_user.id):
        return

    parts = query.data.split(":")
    tour_key = parts[1]
    date_idx = int(parts[2])

    data = load_data()
    dates = data.get(tour_key, [])

    if date_idx >= len(dates):
        await query.edit_message_text("❌ Дата не найдена.")
        return

    item = dates[date_idx]
    label = spots_label(item["spots"])

    keyboard = [
        [InlineKeyboardButton(
            "✏️ Изменить кол-во мест",
            callback_data=f"edit:{tour_key}:{date_idx}",
        )],
        [InlineKeyboardButton(
            "🗑 Удалить дату",
            callback_data=f"del:{tour_key}:{date_idx}",
        )],
        [InlineKeyboardButton(
            "◀️ Назад к датам",
            callback_data=f"tour:{tour_key}",
        )],
    ]

    await query.edit_message_text(
        f"📌 *{item['date']}*\n"
        f"Статус: {label}\n\n"
        f"Что сделать?",
        reply_markup=InlineKeyboardMarkup(keyboard),
        parse_mode="Markdown",
    )


async def delete_date(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    query = update.callback_query
    await query.answer()

    if not is_admin(query.from_user.id):
        return

    parts = query.data.split(":")
    tour_key = parts[1]
    date_idx = int(parts[2])

    data = load_data()
    dates = data.get(tour_key, [])

    if date_idx < len(dates):
        removed = dates.pop(date_idx)
        save_data(data)
        await query.answer(f"✅ Дата «{removed['date']}» удалена!", show_alert=True)

    await show_tour_dates(query, context, tour_key)


async def edit_spots_start(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    query = update.callback_query
    await query.answer()

    if not is_admin(query.from_user.id):
        return ConversationHandler.END

    parts = query.data.split(":")
    tour_key = parts[1]
    date_idx = int(parts[2])

    context.user_data["edit_tour"] = tour_key
    context.user_data["edit_idx"] = date_idx

    data = load_data()
    item = data[tour_key][date_idx]

    await query.edit_message_text(
        f"✏️ Дата: *{item['date']}*\n"
        f"Текущее кол-во мест: *{item['spots']}*\n\n"
        f"Введите новое количество мест (число):",
        parse_mode="Markdown",
    )
    return WAITING_EDIT_SPOTS


async def edit_spots_receive(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    if not is_admin(update.effective_user.id):
        return ConversationHandler.END

    text = update.message.text.strip()
    try:
        new_spots = int(text)
        if new_spots < 0:
            raise ValueError
    except ValueError:
        await update.message.reply_text("❌ Введите положительное число. Попробуйте ещё:")
        return WAITING_EDIT_SPOTS

    tour_key = context.user_data["edit_tour"]
    date_idx = context.user_data["edit_idx"]

    data = load_data()
    if date_idx < len(data.get(tour_key, [])):
        data[tour_key][date_idx]["spots"] = new_spots
        save_data(data)

        item = data[tour_key][date_idx]
        label = spots_label(new_spots)
        await update.message.reply_text(
            f"✅ Обновлено!\n\n"
            f"📌 {item['date']} — {label}\n\n"
            f"Используйте /tours для продолжения.",
        )
    else:
        await update.message.reply_text("❌ Дата не найдена. /tours")

    return ConversationHandler.END


async def add_date_start(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    query = update.callback_query
    await query.answer()

    if not is_admin(query.from_user.id):
        return ConversationHandler.END

    tour_key = query.data.split(":")[1]
    context.user_data["add_tour"] = tour_key

    await query.edit_message_text(
        f"➕ *Добавление даты*\n"
        f"Тур: {TOUR_NAMES.get(tour_key)}\n\n"
        f"Введите дату (например: «15 — 20 июля»):",
        parse_mode="Markdown",
    )
    return WAITING_NEW_DATE


async def add_date_receive(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    if not is_admin(update.effective_user.id):
        return ConversationHandler.END

    context.user_data["new_date"] = update.message.text.strip()
    await update.message.reply_text(
        f"📅 Дата: *{context.user_data['new_date']}*\n\n"
        f"Введите количество свободных мест (число):",
        parse_mode="Markdown",
    )
    return WAITING_NEW_SPOTS


async def add_spots_receive(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    if not is_admin(update.effective_user.id):
        return ConversationHandler.END

    text = update.message.text.strip()
    try:
        spots = int(text)
        if spots < 0:
            raise ValueError
    except ValueError:
        await update.message.reply_text("❌ Введите положительное число:")
        return WAITING_NEW_SPOTS

    tour_key = context.user_data["add_tour"]
    new_date = context.user_data["new_date"]

    data = load_data()
    data.setdefault(tour_key, []).append({"date": new_date, "spots": spots})
    save_data(data)

    label = spots_label(spots)
    await update.message.reply_text(
        f"✅ Дата добавлена!\n\n"
        f"📌 {new_date} — {label}\n\n"
        f"Используйте /tours для продолжения.",
    )
    return ConversationHandler.END


async def back_to_tours(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    query = update.callback_query
    await query.answer()

    if not is_admin(query.from_user.id):
        return

    keyboard = [
        [InlineKeyboardButton(name, callback_data=f"tour:{key}")]
        for key, name in TOUR_NAMES.items()
    ]
    await query.edit_message_text(
        "🗺 Выберите тур:",
        reply_markup=InlineKeyboardMarkup(keyboard),
    )


async def cancel(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    await update.message.reply_text("❌ Отменено. /tours")
    return ConversationHandler.END


def main() -> None:
    app = Application.builder().token(BOT_TOKEN).build()

    # Conversation for adding a date
    add_conv = ConversationHandler(
        entry_points=[CallbackQueryHandler(add_date_start, pattern=r"^add:")],
        states={
            WAITING_NEW_DATE: [MessageHandler(filters.TEXT & ~filters.COMMAND, add_date_receive)],
            WAITING_NEW_SPOTS: [MessageHandler(filters.TEXT & ~filters.COMMAND, add_spots_receive)],
        },
        fallbacks=[CommandHandler("cancel", cancel)],
        per_message=False,
    )

    # Conversation for editing spots
    edit_conv = ConversationHandler(
        entry_points=[CallbackQueryHandler(edit_spots_start, pattern=r"^edit:")],
        states={
            WAITING_EDIT_SPOTS: [MessageHandler(filters.TEXT & ~filters.COMMAND, edit_spots_receive)],
        },
        fallbacks=[CommandHandler("cancel", cancel)],
        per_message=False,
    )

    # Register handlers (order matters: conversations first)
    app.add_handler(add_conv)
    app.add_handler(edit_conv)
    app.add_handler(CommandHandler("start", start))
    app.add_handler(CommandHandler("help", help_cmd))
    app.add_handler(CommandHandler("tours", tours))
    app.add_handler(CallbackQueryHandler(tour_selected, pattern=r"^tour:"))
    app.add_handler(CallbackQueryHandler(date_selected, pattern=r"^date:"))
    app.add_handler(CallbackQueryHandler(delete_date, pattern=r"^del:"))
    app.add_handler(CallbackQueryHandler(back_to_tours, pattern=r"^back:tours"))

    logger.info("🤖 Бот запущен!")
    app.run_polling(allowed_updates=Update.ALL_TYPES)


if __name__ == "__main__":
    main()
