// Auto-generated by bot.py — do not edit manually
var TOURS_DATA = {
  "tour1": [
    {
      "date": "29 мая — 2 июня",
      "spots": 10
    },
    {
      "date": "2 — 6 июня",
      "spots": 12
    },
    {
      "date": "6 — 10 июня",
      "spots": 10
    },
    {
      "date": "10 - 14 июня",
      "spots": 20
    },
    {
      "date": "16 - 20 июля",
      "spots": 20
    },
    {
      "date": "20 - 24 августа",
      "spots": 20
    },
    {
      "date": "28 августа - 1 сентября",
      "spots": 20
    }
  ],
  "tour2": [
    {
      "date": "21 - 27 августа",
      "spots": 10
    },
    {
      "date": "28 августа - 3 сентября 2027",
      "spots": 10
    }
  ]
};
