// Auto-generated by bot.py — do not edit manually
var TOURS_DATA = {
  "tour1": [
    {
      "date": "4 — 8 мая",
      "spots": 15
    },
    {
      "date": "7 — 11 мая",
      "spots": 15
    },
    {
      "date": "29 мая — 2 июня",
      "spots": 0
    },
    {
      "date": "2 — 6 июня",
      "spots": 10
    },
    {
      "date": "6 — 10 июня",
      "spots": 10
    }
  ],
  "tour2": [
    {
      "date": "22 авг — 2 сен 2026",
      "spots": 10
    },
    {
      "date": "12 - 15 мая",
      "spots": 5
    },
    {
      "date": "12 - 15 января",
      "spots": 4
    }
  ]
};
