// Auto-generated by bot.py — do not edit manually
var TOURS_DATA = {
  "tour1": [
    {
      "date": "2 — 6 июня",
      "spots": 12
    },
    {
      "date": "6 — 10 июня",
      "spots": 10
    },
    {
      "date": "20 - 24 августа",
      "spots": 20
    },
    {
      "date": "27-31 августа",
      "spots": 20
    },
    {
      "date": "24-28 сентября",
      "spots": 20
    },
    {
      "date": "1-5 октября",
      "spots": 20
    }
  ],
  "tour2": [
    {
      "date": "28 августа - 3 сентября 2027",
      "spots": 10
    },
    {
      "date": "4 - 10 сентября 2027",
      "spots": 10
    },
    {
      "date": "21-27 августа 2027 г.",
      "spots": 10
    }
  ]
};
